#!/bin/bash

echo "╔══════════════════════════════════════════════════════════╗"
echo "║      🧪 TESTE NAVEGADOR - CRIAR AUTOMAÇÃO                ║"
echo "╚══════════════════════════════════════════════════════════╝"
echo ""

echo "🌐 INSTRUÇÕES PARA TESTE:"
echo ""
echo "1️⃣  Abra o navegador em: http://localhost:8080"
echo ""
echo "2️⃣  Acesse: Automações → Criar Nova"
echo "    URL: http://localhost:8080/automations/create"
echo ""
echo "3️⃣  Adicionar Node:"
echo "    • Clique no botão '+' ou área do canvas"
echo "    • Modal com 3 ABAS deve abrir:"
echo "      ✓ System Tools (4)"
echo "      ✓ Agentes (N)"
echo "      ✓ MCPs (0+)"
echo ""
echo "4️⃣  Selecionar 'Manual Trigger':"
echo "    • Na aba 'System Tools'"
echo "    • Clique no card"
echo "    • Node ELEGANTE deve aparecer no canvas"
echo ""
echo "5️⃣  Configurar Node:"
echo "    • Clique no ícone ⚙️ (Settings) do node"
echo "    • Modal de configuração deve abrir"
echo "    • ✅ NÃO DEVE dar erro"
echo "    • ✅ DEVE mostrar campos de configuração"
echo "    • ✅ DEVE carregar parâmetros da tool"
echo ""
echo "6️⃣  Adicionar Segundo Node:"
echo "    • Adicione 'Condition Flex'"
echo "    • Conecte os dois nodes"
echo "    • Veja EDGE COM CURVA entre eles"
echo ""
echo "7️⃣  Salvar Automação:"
echo "    • Dê um nome: 'Teste Workflow'"
echo "    • Clique em 'Salvar'"
echo "    • ✅ Deve salvar sem erros"
echo ""
echo "8️⃣  Executar Automação:"
echo "    • Clique em '▶ Executar'"
echo "    • Veja logs em tempo real"
echo "    • ✅ NÃO DEVE dar 'Tool not found'"
echo ""
echo "═══════════════════════════════════════════════════════════"
echo ""
echo "🔍 SE DER ERRO:"
echo "   • Abra Console do navegador (F12)"
echo "   • Veja mensagem de erro"
echo "   • Relate o erro"
echo ""
echo "✅ SE FUNCIONAR:"
echo "   • Configuração abre corretamente"
echo "   • Nodes salvam toolId"
echo "   • Execução funciona"
echo ""
echo "═══════════════════════════════════════════════════════════"
