/**
 * E2E Tests - Advanced Real-World Use Cases
 * Complex scenarios using System Tools + MCPs + Multi-Agent workflows
 */

import { FlowEngineV2 } from '../../source/core/flowEngineV2.js';
import { FlowDefinition } from '../../source/core/flowTypes.js';
import { registerAllTools } from '../../source/tools/registerAllTools.js';
import { tmpdir } from 'os';
import { join } from 'path';
import { rm, mkdir, writeFile, readFile } from 'fs/promises';
import { randomBytes } from 'crypto';

const generateId = () => randomBytes(8).toString('hex');

describe('E2E - Advanced Real-World Use Cases - REAL', () => {
  let sandboxDir: string;

  beforeAll(async () => {
    await registerAllTools();
  });

  beforeEach(async () => {
    sandboxDir = join(tmpdir(), `flui-advanced-${generateId()}`);
    await mkdir(sandboxDir, { recursive: true });
  });

  afterEach(async () => {
    await rm(sandboxDir, { recursive: true, force: true });
  });

  it('ADVANCED USE CASE 1: Multi-Agent File Processing Pipeline', async () => {
    /**
     * Complex scenario: Multiple agents working together
     * Agent 1: Collects data files
     * Agent 2: Processes each file
     * Agent 3: Aggregates results
     * Agent 4: Generates reports
     */
    
    // Create sample data files
    const dataFiles = [
      { name: 'sales-2024-01.csv', content: 'product,amount\nWidget,100\nGadget,200' },
      { name: 'sales-2024-02.csv', content: 'product,amount\nWidget,150\nGadget,250' },
      { name: 'sales-2024-03.csv', content: 'product,amount\nWidget,120\nGadget,180' },
    ];

    // Write data files
    for (const file of dataFiles) {
      await writeFile(join(sandboxDir, file.name), file.content);
    }

    const flow: FlowDefinition = {
      id: generateId(),
      name: 'Multi-Agent Data Processing',
      description: 'Complex multi-agent workflow',
      version: '1.0',
      nodes: [
        // Agent 1: Discover all CSV files
        {
          id: 'agent1-discover',
          name: 'Agent 1: Discover Data Files',
          type: 'tool',
          config: {
            toolId: 'file-search',
            pattern: '*.csv',
            path: sandboxDir,
            recursive: false,
            sandboxPath: sandboxDir,
          },
        },
        // Agent 2: Read all files
        {
          id: 'agent2-read',
          name: 'Agent 2: Read All Files',
          type: 'tool',
          config: {
            toolId: 'files-read-batch',
            paths: dataFiles.map(f => join(sandboxDir, f.name)),
            continueOnError: false,
            sandboxPath: sandboxDir,
          },
        },
        // Agent 2: Process data - count Widget sales
        {
          id: 'agent2-process-widgets',
          name: 'Agent 2: Count Widget Sales',
          type: 'tool',
          config: {
            toolId: 'text-search',
            pattern: 'Widget',
            path: sandboxDir,
            recursive: true,
            sandboxPath: sandboxDir,
          },
        },
        // Agent 2: Process data - count Gadget sales
        {
          id: 'agent2-process-gadgets',
          name: 'Agent 2: Count Gadget Sales',
          type: 'tool',
          config: {
            toolId: 'text-search',
            pattern: 'Gadget',
            path: sandboxDir,
            recursive: true,
            sandboxPath: sandboxDir,
          },
        },
        // Agent 3: Create aggregation summary
        {
          id: 'agent3-aggregate',
          name: 'Agent 3: Aggregate Results',
          type: 'tool',
          config: {
            toolId: 'file-write',
            path: join(sandboxDir, 'aggregation.txt'),
            content: 'Data aggregation:\n- Widget sales processed\n- Gadget sales processed\n- Q1 2024 analysis complete',
            sandboxPath: sandboxDir,
          },
        },
        // Agent 4: Generate final report
        {
          id: 'agent4-report',
          name: 'Agent 4: Generate Final Report',
          type: 'tool',
          config: {
            toolId: 'file-write',
            path: join(sandboxDir, 'final-report.md'),
            content: '# Q1 2024 Sales Report\n\n## Summary\n\nAll data processed successfully.\n\n## Data Sources\n- sales-2024-01.csv\n- sales-2024-02.csv\n- sales-2024-03.csv\n\n## Products Analyzed\n- Widgets\n- Gadgets\n\n---\n*Report generated by Multi-Agent System*',
            sandboxPath: sandboxDir,
          },
        },
      ],
      edges: [
        { id: 'e1', source: 'agent1-discover', target: 'agent2-read' },
        { id: 'e2', source: 'agent2-read', target: 'agent2-process-widgets' },
        { id: 'e3', source: 'agent2-read', target: 'agent2-process-gadgets' },
        { id: 'e4', source: 'agent2-process-widgets', target: 'agent3-aggregate' },
        { id: 'e5', source: 'agent2-process-gadgets', target: 'agent3-aggregate' },
        { id: 'e6', source: 'agent3-aggregate', target: 'agent4-report' },
      ],
      startNodeId: 'agent1-discover',
    };

    const engine = new FlowEngineV2(flow);
    const result = await engine.execute();

    if (result.status === 'failed') {
      console.error('❌ Multi-Agent workflow failed:', result.error);
      const failedLogs = result.logs.filter(l => l.status === 'failed');
      failedLogs.forEach(log => console.error('  -', log.nodeName, ':', log.message, log.error));
    }

    expect(result.status).toBe('completed');
    
    // Verify all agents executed
    expect(result.nodeResults['agent1-discover']).toBeTruthy();
    expect(result.nodeResults['agent2-read']).toBeTruthy();
    expect(result.nodeResults['agent2-process-widgets']).toBeTruthy();
    expect(result.nodeResults['agent2-process-gadgets']).toBeTruthy();
    expect(result.nodeResults['agent3-aggregate']).toBeTruthy();
    expect(result.nodeResults['agent4-report']).toBeTruthy();
    
    // Verify report was created
    const report = await readFile(join(sandboxDir, 'final-report.md'), 'utf-8');
    expect(report).toContain('Q1 2024 Sales Report');
    expect(report).toContain('Multi-Agent System');
  }, 60000);

  it('ADVANCED USE CASE 2: Automated Code Review Workflow', async () => {
    /**
     * Scenario: Automated code quality review
     * 1. Create source code files
     * 2. Search for code smells (console.log, TODO, FIXME)
     * 3. Check for missing error handling
     * 4. Generate review report with recommendations
     */
    
    const sourceCode = `function processData(data) {
  console.log('Processing:', data); // TODO: Remove debug log
  
  const result = data.map(item => {
    return item * 2;
  });
  
  // FIXME: Add error handling here
  return result;
}

function calculate(x, y) {
  console.log('Calculating...');
  return x + y;
}`;

    await writeFile(join(sandboxDir, 'app.js'), sourceCode);

    const flow: FlowDefinition = {
      id: generateId(),
      name: 'Automated Code Review',
      description: 'Quality analysis workflow',
      version: '1.0',
      nodes: [
        {
          id: 'read-source',
          name: 'Read Source Code',
          type: 'tool',
          config: {
            toolId: 'file-read',
            path: join(sandboxDir, 'app.js'),
            sandboxPath: sandboxDir,
          },
        },
        {
          id: 'find-console-logs',
          name: 'Find Debug Logs',
          type: 'tool',
          config: {
            toolId: 'text-search',
            pattern: 'console\\.log',
            path: join(sandboxDir, 'app.js'),
            regex: true,
            sandboxPath: sandboxDir,
          },
        },
        {
          id: 'find-todos',
          name: 'Find TODO Comments',
          type: 'tool',
          config: {
            toolId: 'text-search',
            pattern: 'TODO',
            path: join(sandboxDir, 'app.js'),
            sandboxPath: sandboxDir,
          },
        },
        {
          id: 'find-fixmes',
          name: 'Find FIXME Comments',
          type: 'tool',
          config: {
            toolId: 'text-search',
            pattern: 'FIXME',
            path: join(sandboxDir, 'app.js'),
            sandboxPath: sandboxDir,
          },
        },
        {
          id: 'check-error-handling',
          name: 'Check Error Handling',
          type: 'tool',
          config: {
            toolId: 'text-search',
            pattern: 'try\\s*\\{|catch\\s*\\(',
            path: join(sandboxDir, 'app.js'),
            regex: true,
            sandboxPath: sandboxDir,
          },
        },
        {
          id: 'generate-review',
          name: 'Generate Review Report',
          type: 'tool',
          config: {
            toolId: 'file-write',
            path: join(sandboxDir, 'code-review.md'),
            content: `# Code Review Report

## Issues Found

### 🔴 Critical
- Missing error handling (FIXME found)
- Debug logs left in code

### 🟡 Warnings
- TODO comments present
- Multiple console.log statements

## Recommendations
1. Remove all console.log statements before production
2. Add try-catch blocks for error handling
3. Address all TODO/FIXME comments
4. Consider using a proper logging library

---
*Generated by Automated Code Review System*`,
            sandboxPath: sandboxDir,
          },
        },
      ],
      edges: [
        { id: 'e1', source: 'read-source', target: 'find-console-logs' },
        { id: 'e2', source: 'read-source', target: 'find-todos' },
        { id: 'e3', source: 'read-source', target: 'find-fixmes' },
        { id: 'e4', source: 'read-source', target: 'check-error-handling' },
        { id: 'e5', source: 'find-console-logs', target: 'generate-review' },
        { id: 'e6', source: 'find-todos', target: 'generate-review' },
        { id: 'e7', source: 'find-fixmes', target: 'generate-review' },
        { id: 'e8', source: 'check-error-handling', target: 'generate-review' },
      ],
      startNodeId: 'read-source',
    };

    const engine = new FlowEngineV2(flow);
    const result = await engine.execute();

    expect(result.status).toBe('completed');
    
    // Verify review was generated
    const review = await readFile(join(sandboxDir, 'code-review.md'), 'utf-8');
    expect(review).toContain('Code Review Report');
    expect(review).toContain('console.log');
    expect(review).toContain('error handling');
  }, 30000);

  it('ADVANCED USE CASE 3: Document Processing and Analysis', async () => {
    /**
     * Scenario: Process multiple documents
     * 1. Create various document types
     * 2. Extract keywords from each
     * 3. Generate document index
     * 4. Create searchable catalog
     */
    
    const documents = [
      { name: 'doc1.txt', content: 'JavaScript TypeScript Node.js Express API REST GraphQL' },
      { name: 'doc2.txt', content: 'Python Django Flask FastAPI Machine Learning AI' },
      { name: 'doc3.txt', content: 'React Vue Angular TypeScript Component State Props' },
    ];

    for (const doc of documents) {
      await writeFile(join(sandboxDir, doc.name), doc.content);
    }

    const flow: FlowDefinition = {
      id: generateId(),
      name: 'Document Processing Pipeline',
      description: 'Extract and index document content',
      version: '1.0',
      nodes: [
        {
          id: 'find-docs',
          name: 'Find All Documents',
          type: 'tool',
          config: {
            toolId: 'file-search',
            pattern: '*.txt',
            path: sandboxDir,
            recursive: false,
            sandboxPath: sandboxDir,
          },
        },
        {
          id: 'read-docs',
          name: 'Read All Documents',
          type: 'tool',
          config: {
            toolId: 'files-read-batch',
            paths: documents.map(d => join(sandboxDir, d.name)),
            continueOnError: false,
            sandboxPath: sandboxDir,
          },
        },
        {
          id: 'extract-javascript-keywords',
          name: 'Extract JavaScript Keywords',
          type: 'tool',
          config: {
            toolId: 'text-search',
            pattern: 'JavaScript|TypeScript|Node\\.js',
            path: sandboxDir,
            regex: true,
            recursive: true,
            sandboxPath: sandboxDir,
          },
        },
        {
          id: 'extract-python-keywords',
          name: 'Extract Python Keywords',
          type: 'tool',
          config: {
            toolId: 'text-search',
            pattern: 'Python|Django|Flask',
            path: sandboxDir,
            regex: true,
            recursive: true,
            sandboxPath: sandboxDir,
          },
        },
        {
          id: 'extract-framework-keywords',
          name: 'Extract Framework Keywords',
          type: 'tool',
          config: {
            toolId: 'text-search',
            pattern: 'React|Vue|Angular|Express',
            path: sandboxDir,
            regex: true,
            recursive: true,
            sandboxPath: sandboxDir,
          },
        },
        {
          id: 'create-index',
          name: 'Create Document Index',
          type: 'tool',
          config: {
            toolId: 'file-write',
            path: join(sandboxDir, 'index.md'),
            content: `# Document Index

## Technologies Found

### Languages
- JavaScript/TypeScript
- Python

### Frameworks
- Express, React, Vue, Angular
- Django, Flask, FastAPI

### Concepts
- API, REST, GraphQL
- Machine Learning, AI
- Components, State Management

---
*Index generated automatically*`,
            sandboxPath: sandboxDir,
          },
        },
      ],
      edges: [
        { id: 'e1', source: 'find-docs', target: 'read-docs' },
        { id: 'e2', source: 'read-docs', target: 'extract-javascript-keywords' },
        { id: 'e3', source: 'read-docs', target: 'extract-python-keywords' },
        { id: 'e4', source: 'read-docs', target: 'extract-framework-keywords' },
        { id: 'e5', source: 'extract-javascript-keywords', target: 'create-index' },
        { id: 'e6', source: 'extract-python-keywords', target: 'create-index' },
        { id: 'e7', source: 'extract-framework-keywords', target: 'create-index' },
      ],
      startNodeId: 'find-docs',
    };

    const engine = new FlowEngineV2(flow);
    const result = await engine.execute();

    expect(result.status).toBe('completed');
    
    // Verify index was created
    const index = await readFile(join(sandboxDir, 'index.md'), 'utf-8');
    expect(index).toContain('Document Index');
    expect(index).toContain('JavaScript/TypeScript');
    expect(index).toContain('Python');
  }, 30000);

  it('ADVANCED USE CASE 4: Build Automation with Multiple Stages', async () => {
    /**
     * Scenario: Complete build pipeline
     * 1. Setup project structure
     * 2. Write source files
     * 3. Run linting (pattern checks)
     * 4. Run tests (execute shell)
     * 5. Build artifacts
     * 6. Generate build report
     */
    
    const flow: FlowDefinition = {
      id: generateId(),
      name: 'Build Automation Pipeline',
      description: 'Full CI/CD workflow',
      version: '1.0',
      nodes: [
        {
          id: 'setup-structure',
          name: 'Setup Project Structure',
          type: 'tool',
          config: {
            toolId: 'shell-exec',
            command: `mkdir -p ${join(sandboxDir, 'src')} ${join(sandboxDir, 'test')} ${join(sandboxDir, 'dist')}`,
            timeout: 5000,
            sandboxPath: sandboxDir,
          },
        },
        {
          id: 'create-source',
          name: 'Create Source Files',
          type: 'tool',
          config: {
            toolId: 'file-write',
            path: join(sandboxDir, 'src', 'index.js'),
            content: 'module.exports = { version: "1.0.0" };',
            sandboxPath: sandboxDir,
          },
        },
        {
          id: 'create-tests',
          name: 'Create Test Files',
          type: 'tool',
          config: {
            toolId: 'file-write',
            path: join(sandboxDir, 'test', 'index.test.js'),
            content: 'const assert = require("assert");\nassert.ok(true);',
            sandboxPath: sandboxDir,
          },
        },
        {
          id: 'lint-check',
          name: 'Run Lint Checks',
          type: 'tool',
          config: {
            toolId: 'text-search',
            pattern: 'module\\.exports|require',
            path: join(sandboxDir, 'src'),
            regex: true,
            recursive: true,
            sandboxPath: sandboxDir,
          },
        },
        {
          id: 'count-files',
          name: 'Count Source Files',
          type: 'tool',
          config: {
            toolId: 'file-search',
            pattern: '*.js',
            path: sandboxDir,
            recursive: true,
            sandboxPath: sandboxDir,
          },
        },
        {
          id: 'create-build-artifact',
          name: 'Create Build Artifact',
          type: 'tool',
          config: {
            toolId: 'file-write',
            path: join(sandboxDir, 'dist', 'bundle.js'),
            content: '// Build v1.0.0\nmodule.exports={version:"1.0.0"};',
            sandboxPath: sandboxDir,
          },
        },
        {
          id: 'generate-build-report',
          name: 'Generate Build Report',
          type: 'tool',
          config: {
            toolId: 'file-write',
            path: join(sandboxDir, 'BUILD_REPORT.md'),
            content: `# Build Report

## Status: ✅ SUCCESS

## Build Steps
1. ✅ Project structure created
2. ✅ Source files written
3. ✅ Test files created
4. ✅ Lint checks passed
5. ✅ Build artifact created

## Artifacts
- dist/bundle.js

## Version: 1.0.0

---
*Build completed at ${new Date().toISOString()}*`,
            sandboxPath: sandboxDir,
          },
        },
      ],
      edges: [
        { id: 'e1', source: 'setup-structure', target: 'create-source' },
        { id: 'e2', source: 'create-source', target: 'create-tests' },
        { id: 'e3', source: 'create-tests', target: 'lint-check' },
        { id: 'e4', source: 'lint-check', target: 'count-files' },
        { id: 'e5', source: 'count-files', target: 'create-build-artifact' },
        { id: 'e6', source: 'create-build-artifact', target: 'generate-build-report' },
      ],
      startNodeId: 'setup-structure',
    };

    const engine = new FlowEngineV2(flow);
    const result = await engine.execute();

    expect(result.status).toBe('completed');
    
    // Verify build artifact
    const artifact = await readFile(join(sandboxDir, 'dist', 'bundle.js'), 'utf-8');
    expect(artifact).toContain('1.0.0');
    
    // Verify build report
    const report = await readFile(join(sandboxDir, 'BUILD_REPORT.md'), 'utf-8');
    expect(report).toContain('SUCCESS');
    expect(report).toContain('bundle.js');
  }, 30000);

  it('ADVANCED USE CASE 5: Data Migration and Validation', async () => {
    /**
     * Scenario: Migrate data from old format to new format
     * 1. Read old format data
     * 2. Transform data structure
     * 3. Validate transformed data
     * 4. Write new format
     * 5. Generate migration report
     */
    
    const oldFormatData = `name:John|age:30|city:NYC
name:Jane|age:25|city:LA
name:Bob|age:35|city:SF`;

    await writeFile(join(sandboxDir, 'old-data.txt'), oldFormatData);

    const flow: FlowDefinition = {
      id: generateId(),
      name: 'Data Migration Pipeline',
      description: 'Transform and validate data format',
      version: '1.0',
      nodes: [
        {
          id: 'read-old-format',
          name: 'Read Old Format',
          type: 'tool',
          config: {
            toolId: 'file-read',
            path: join(sandboxDir, 'old-data.txt'),
            sandboxPath: sandboxDir,
          },
        },
        {
          id: 'transform-step-1',
          name: 'Transform: Replace Pipes',
          type: 'tool',
          config: {
            toolId: 'text-replace',
            path: join(sandboxDir, 'old-data.txt'),
            find: '|',
            replace: ',',
            replaceAll: true,
            sandboxPath: sandboxDir,
          },
        },
        {
          id: 'transform-step-2',
          name: 'Transform: Replace Colons',
          type: 'tool',
          config: {
            toolId: 'text-replace',
            path: join(sandboxDir, 'old-data.txt'),
            find: ':',
            replace: '=',
            replaceAll: true,
            sandboxPath: sandboxDir,
          },
        },
        {
          id: 'validate-format',
          name: 'Validate New Format',
          type: 'tool',
          config: {
            toolId: 'text-search',
            pattern: '=.*,',
            path: join(sandboxDir, 'old-data.txt'),
            regex: true,
            sandboxPath: sandboxDir,
          },
        },
        {
          id: 'save-new-format',
          name: 'Save New Format',
          type: 'tool',
          config: {
            toolId: 'file-read',
            path: join(sandboxDir, 'old-data.txt'),
            sandboxPath: sandboxDir,
          },
        },
        {
          id: 'create-migration-log',
          name: 'Create Migration Log',
          type: 'tool',
          config: {
            toolId: 'file-write',
            path: join(sandboxDir, 'migration.log'),
            content: `Migration Log
=============

Start Time: ${new Date().toISOString()}
Records Processed: 3
Format Changed: pipe-colon → comma-equals
Status: COMPLETED

Old Format: name:John|age:30
New Format: name=John,age=30

Validation: PASSED`,
            sandboxPath: sandboxDir,
          },
        },
      ],
      edges: [
        { id: 'e1', source: 'read-old-format', target: 'transform-step-1' },
        { id: 'e2', source: 'transform-step-1', target: 'transform-step-2' },
        { id: 'e3', source: 'transform-step-2', target: 'validate-format' },
        { id: 'e4', source: 'validate-format', target: 'save-new-format' },
        { id: 'e5', source: 'save-new-format', target: 'create-migration-log' },
      ],
      startNodeId: 'read-old-format',
    };

    const engine = new FlowEngineV2(flow);
    const result = await engine.execute();

    expect(result.status).toBe('completed');
    
    // Verify data transformation
    const transformedData = await readFile(join(sandboxDir, 'old-data.txt'), 'utf-8');
    expect(transformedData).toContain('name=John');
    expect(transformedData).toContain(',age=30');
    expect(transformedData).not.toContain('|');
    expect(transformedData).not.toContain(':');
    
    // Verify migration log
    const migrationLog = await readFile(join(sandboxDir, 'migration.log'), 'utf-8');
    expect(migrationLog).toContain('Migration Log');
    expect(migrationLog).toContain('COMPLETED');
  }, 30000);
});
